Fix java.lang.NoSuchMethodError: genj.view.ToolBar.add(Ljavax/swing/Action;)V By moving ToolBar from genj.view to ancestris.swing This will force a new svn revision for all modules that use ToolBar. Before that unmodified modules were not updated ans as add(Action has changed from void type to JButton (like in JToolBar) this raises an exception